### ISSUE TITLE
Add an Avian2D physics backend

### ISSUE THREAD

**Issue by adrien-bon** [adrien-bon/bevy_ecs_tiled#14]
We currently support `rapier` as a physics backend: we can automatically add colliders based on the Tiled map.

The idea would be to also add support for `Avian2D` which is another popular 'physic-related' crate.

**Comment by giusdp** [comment]
Hi, I've added avian2d to bevy_ecs_tiled locally to use for my projects. If it's fine for you I can open a PR to contribute it, but it might need some more polishing.

**Comment by adrien-bon** [comment]
Hi, yes please do ! :)

If you can put your code in a dedicated file under `./src/physics/avian.rs` that would be nice.
Don't worry about the polishing, I can try to help!
The idea I had was to get more or less the same API as what we currently have for `Rapier` and the same kind of examples.

Thanks!
