### ISSUE TITLE
Warn when no physics feature selected?

### ISSUE THREAD

**Issue by dynastydi** [adrien-bon/bevy_ecs_tiled#43]
Hi. Love the rapier & avian integration design.

Accepting that a physics book page is WIP, I'd like to suggest a warning when no physics feature is selected - perhaps, for example, conditional on `PhysicsBackend::Avian` or `Rapier` being selected in `tiled_settings`.

Current behaviour means avian (and presumably rapier, untested) can run perfectly for all other entities, but won't spawn colliders on the tilemap, without panicking or giving any warnings. `collider_callback` also won't run, silently. Particularly stupid users (me) might find this very confusing and spend an embarrassing amount of time tearing their hair out before figuring out it's just a missing feature flag :)

**Comment by adrien-bon** [comment]
Hi,

First of all, thanks for the issue, it's always nice to get some feedback!

Regarding your proposal, this part of the crate have actually drastically changed.
If you take a look at the [`dev` branch](https://github.com/adrien-bon/bevy_ecs_tiled/tree/dev), the physics backend selection through `tiled_settings` is gone. Now we need to instanciate a dedicated physics plugin, holding the information of which backend to use. This plugin cannot be used if the corresponding feature is not enabled.
You can have a look to the [corresponding example](https://github.com/adrien-bon/bevy_ecs_tiled/blob/dev/examples/physics_avian_settings.rs#L20) or the "soon to be published" [book section](https://github.com/adrien-bon/bevy_ecs_tiled/blob/dev/book/src/guides/physics.md).
Let me know if it works for you: always open to suggestions! :)

FYI, I plan to release this at the same time I update for bevy 0.15, once all dependent crates are up to date.

**Comment by dynastydi** [comment]
Thanks for the quick reply.

My mistake for not checking dev - yes this is a great antidote to the confusion I experienced. Much more transparent to rely on a separate plugin instantiation for the auto-collider feature, and very Bevy-like.

Since opening this issue I've been working more with v0.3.10. Being able to seamlessly combine `avian` and `bevy_ecs_tilemap` makes Bevy feel much more like a complete engine. Nice work!
