### ISSUE TITLE
Events and Helpers

### ISSUE THREAD

**Issue by JtotheThree** [adrien-bon/bevy_ecs_tiled#44]
Adding some events after the level is loaded would be nice to use for loading screens etc.

I am more than happy to contribute to add them in. I have one thought though, I would think it would be best to add say a TiledMapLoaded event AFTER the custom object/tiles have also been processed but I'm not sure the best way to determine how all of that has been processed. Maybe there's something we could do with a Local Resource on a event reader to determine the custom properties have been processed?

Another thing that would be helpful is adding in a helper function to map the grid position of a bevy transform (i.e. mouse cursor position) to grid coordinates.

**Comment by adrien-bon** [comment]
Hey!
Map loading events are now available since release of [v0.4.0](https://github.com/adrien-bon/bevy_ecs_tiled/releases/tag/v0.4.0) so I'm closing this issue.
Feel free to open another one if there are more questions.
