### ISSUE TITLE
remove the leftover `dbg!` call

### ISSUE THREAD

**Issue by shekohex** [adrien-bon/bevy_ecs_tiled#53]
There is an annoying `dbg` call here:
https://github.com/adrien-bon/bevy_ecs_tiled/blob/main/src%2Fasset.rs#L166-L167

This should be replaced by `debug!` or even better a `trace!` instead. 

Happy to open a PR with this small chance.

**Comment by adrien-bon** [comment]
Hi!

Thanks for reporting the issue.

This `dbg()` call was added then forgotten during rework on properties.
Yes, please go ahead and remove it!
