### ISSUE TITLE
Animated tiles missing a tile/frame

### ISSUE THREAD

**Issue by ilyvion** [adrien-bon/bevy_ecs_tiled#61]
(with the caveat that I'm using the as-of-yet unmerged #45 PR since I'm on 0.15 and that this may not have been a problem in the earlier versions)

I tried using this crate for the first time and wanted to use animated tiles, but I noticed that a frame was always missing from the animation in Bevy compared to in Tiled. I looked through the relevant code and noticed that the `AnimatedTile` is created using `last_tile.tile_id` as its `end` value:
https://github.com/adrien-bon/bevy_ecs_tiled/blob/86e489ad42941a40f329628695ea5232d427875d/src/loader.rs#L578-L582

The documentation for `AnimatedTile::end` is "The end frame index in the tilemap atlas/array (exclusive)." That "exclusive" made me think that it might be necessary to add 1 to the `last_tile.tile_id` since we want to include the last tile of the animation that Tiled provides to us, not exclude it. And sure enough, by changing the code above to
```rust
Some(AnimatedTile {
    start: first_tile.tile_id,
    end: last_tile.tile_id + 1, // added a `+ 1` here
    speed: 1000. / first_tile.duration as f32, // duration is in ms and we want a 'frames per second' speed
})
```
my animated tiles are suddenly not missing tiles/frames anymore.

**Comment by adrien-bon** [comment]
Hi,
thanks for the issue!
Seems like it's a bug since the feature was added.
I'll fix that in the next release
