### ISSUE TITLE
Polygons are always created as convex, but Tiled polygons can be concave

### ISSUE THREAD

**Issue by alanbaumgartner** [adrien-bon/bevy_ecs_tiled#65]
Got another one for ya 😄 

In Bevy
![image](https://github.com/user-attachments/assets/00117cd1-5999-471e-8a35-3bd48ad629b1)

In Tiled
![image](https://github.com/user-attachments/assets/fa295281-58c7-470e-99dc-74ece0cc3ef2)

Code
https://github.com/adrien-bon/bevy_ecs_tiled/blob/9d63876bf82913188bfe03b969b08df25a1216d2/src/physics/avian.rs#L73-L91

I think something similar to this could work, could maybe some validation on the length of the input vec being 3 or greater.
```rust
let points = points
    .iter()
    .map(|(x, y)| Vector::new(*x, -*y))
    .collect::<Vec<_>>();

let indices = (0..points.len() as u32 - 1)
    .map(|i| [i, i + 1])
    .chain([[points.len() as u32 - 1, 0]])
    .collect();

let shape = Collider::polyline(
    points,
    Some(indices),
);

(Vector::ZERO, shape)
```

The indices code is similar to what parry does under the hood but with the last index being a pair of the last and first entry.
https://github.com/dimforge/parry/blob/aaeb17f9414c2d801d59609bc7d6ec48eda5fe70/src/shape/polyline.rs#L29-L30

Results in this
![image](https://github.com/user-attachments/assets/2c348b82-c71a-41bd-8b0e-9bc3f0931fe3)

**Comment by adrien-bon** [comment]
Hi,
thanks again for the report! :)

That seems like a good solution that could be applied to both Avian and Rapier backends.
`polyline` actually makes more sense than `convex_hull`.
Could you please open a PR with this for both backends ?

FYI, I won't be there starting tomorrow until after Christmas, so I will probably review this after I'm back.
